services:
  translator:
    build: .
    image: jetson_translator_gpu
    container_name: jetson_translator
    restart: unless-stopped
    env_file: .env
    runtime: nvidia
    network_mode: host
    privileged: true
    volumes:
      - ./models:/app/models
    devices:
      - /dev/snd:/dev/snd
    stdin_open: true
    tty: true
